spring:
  datasource:
    username: root
    password: x5
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   #  hibernate:
   #   ddl-auto: update #     更新或者创建数据表结构
    show-sql: true  #    控制台显示SQL
server:
  servlet:
    context-path: /qinzp
  port: 8081